// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: npm run contracts:gen
//
// schema:contracts/ipc-error.schema.json sha256:ef5d5e7a08803db45ad3dcc7ba05db700836cb2fac2008262265eab1ea21153f
// schema:contracts/template.schema.json sha256:0e4b844f8e1d65490e1a2338e2faff8ab90bca7a62518213622041503ab5e0a8
// schema:contracts/render-comment-params.schema.json sha256:0ca3206549c49ba6e20be05be4de077818b7e5ee0bc33781560e38f3e4624ea4
// schema:contracts/ipc-request.schema.json sha256:6a612e99e195aebb7fdb5b3f570950f885155a076e70cc391bb80ff3edc13edb
// schema:contracts/ipc-response.schema.json sha256:75d6020207f0673fd40b729f68dbee393e3bdb6a5f69e81ab15886994771fd39

/*
  Generated TypeScript interfaces from JSON Schema contracts.
  The repository gate validates the schema sha256 markers above.
*/

export interface IpcError {
  code: string;
  message: string;
  details?: unknown;
}
export interface Template {
  id: string;
  frame: string;
  section: string;
  text: string;
  slots: string[];
  tone?: string;
  indicators?: string[];
}
export interface RenderCommentParams {
  template_id: string;
  slots?: Record<string, string>;
}
export interface IpcRequest {
  id: string;
  method: 'health' | 'list_templates' | 'get_template' | 'render_comment' | 'debug_info';
  params: Record<string, unknown>;
}
export interface IpcResponse<T = unknown> {
  id: string;
  result: T;
  error: IpcError | null;
}

// Method-specific response types (derived from Python sidecar handlers)
export interface HealthResponse {
  status: string;
  version: string;
}

export interface ListTemplatesResponse {
  templates: Template[];
}

export interface RenderCommentResponse {
  text: string;
  char_count: number;
  validation: {
    valid: boolean;
    errors: string[];
    warnings: string[];
  };
}

export interface DebugInfoResponse {
  meipass: string | null;
  frozen: boolean;
  embedded_len: number;
  cwd: string;
  root: string;
}
