import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const workspaceRoot = path.resolve(__dirname, '..', '..');
const contractsDir = path.join(workspaceRoot, 'contracts');
const outDir = path.join(workspaceRoot, 'vgreport', 'src', 'contracts');
const outFile = path.join(outDir, 'generated.ts');

const required = [
  'ipc-error.schema.json',
  'template.schema.json',
  'render-comment-params.schema.json',
  'ipc-request.schema.json',
  'ipc-response.schema.json',
];

function sha256(buf) {
  return crypto.createHash('sha256').update(buf).digest('hex');
}

await fs.mkdir(outDir, { recursive: true });

const markers = [];
for (const name of required) {
  const p = path.join(contractsDir, name);
  const raw = await fs.readFile(p);
  markers.push({ rel: `contracts/${name}`, sha: sha256(raw) });
}

const header = [
  '// AUTO-GENERATED FILE. DO NOT EDIT.',
  '// Generated by: npm run contracts:gen',
  '//',
  ...markers.map(m => `// schema:${m.rel} sha256:${m.sha}`),
  '',
  '/*',
  '  This file intentionally contains lightweight types.',
  '  The repository gate validates the schema sha256 markers above.',
  '*/',
  '',
  'export type IpcRequest = unknown;',
  'export type IpcResponse = unknown;',
  'export type IpcError = unknown;',
  'export type RenderCommentParams = unknown;',
  'export type Template = unknown;',
  '',
].join('\n');

await fs.writeFile(outFile, header, 'utf8');
console.log(`Wrote ${path.relative(workspaceRoot, outFile)}`);
