"""Generate gaps report identifying coverage deficiencies.

This script identifies:
- Indicators with fewer than 2 templates
- Frames with fewer than 3 templates per section

Output: reports/gaps.md
Exit code: 1 if critical gaps exist, 0 otherwise
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

from ruamel.yaml import YAML

WORKSPACE_ROOT = Path(__file__).resolve().parents[1]

# Thresholds
MIN_TEMPLATES_PER_INDICATOR = 2
MIN_TEMPLATES_PER_SECTION = 3


def load_yaml(path: Path) -> dict:
    """Load YAML file and return parsed data."""
    yaml = YAML(typ="safe")
    return yaml.load(path)


def generate_gaps_report() -> int:
    """Generate gaps report and return exit code."""
    # Load data
    templates_path = WORKSPACE_ROOT / "templates" / "comment_templates.yaml"
    indicators_path = WORKSPACE_ROOT / "taxonomy" / "indicators.yaml"
    frames_path = WORKSPACE_ROOT / "taxonomy" / "frames.yaml"

    templates_data = load_yaml(templates_path)
    indicators_data = load_yaml(indicators_path)
    frames_data = load_yaml(frames_path)

    templates = templates_data.get("templates", [])
    indicators = indicators_data.get("indicators", [])
    frames = frames_data.get("frames", [])

    # Build mappings
    frame_names = {f["id"]: f["name"] for f in frames}
    indicator_names = {i["id"]: i["name"] for i in indicators}
    indicator_frames = {i["id"]: i["frame"] for i in indicators}

    # Count templates per indicator
    indicator_counts: dict[str, int] = defaultdict(int)
    for tmpl in templates:
        tmpl_indicators = tmpl.get("indicators", [])
        for ind_id in tmpl_indicators:
            indicator_counts[ind_id] += 1

    # Count templates per frame per section
    frame_section_counts: dict[tuple[str, str], int] = defaultdict(int)
    for tmpl in templates:
        frame_id = tmpl.get("frame")
        section = tmpl.get("section")
        if frame_id and section:
            frame_section_counts[(frame_id, section)] += 1

    # Identify gaps
    indicator_gaps = []
    for ind in indicators:
        ind_id = ind["id"]
        count = indicator_counts.get(ind_id, 0)
        if count < MIN_TEMPLATES_PER_INDICATOR:
            indicator_gaps.append((ind_id, count))

    section_gaps = []
    sections = ["key_learning", "growth", "next_steps"]
    for frame in frames:
        frame_id = frame["id"]
        for section in sections:
            count = frame_section_counts.get((frame_id, section), 0)
            if count < MIN_TEMPLATES_PER_SECTION:
                section_gaps.append((frame_id, section, count))

    # Generate report
    output_path = WORKSPACE_ROOT / "reports" / "gaps.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    critical_gaps_exist = len(indicator_gaps) > 0 or len(section_gaps) > 0

    with output_path.open("w", encoding="utf-8") as f:
        f.write("# Template Coverage Gaps\n\n")
        f.write("> Auto-generated by `scripts/generate_gaps_report.py`\n\n")

        if not critical_gaps_exist:
            f.write("## ✅ No Critical Gaps\n\n")
            f.write("All indicators have at least 2 templates.\n")
            f.write("All frame sections have at least 3 templates.\n")
        else:
            f.write("## ⚠️ Gaps Identified\n\n")

            # Indicator gaps
            if indicator_gaps:
                f.write(f"### Indicators with <{MIN_TEMPLATES_PER_INDICATOR} Templates\n\n")
                f.write("| Indicator | Frame | Count | Status |\n")
                f.write("|-----------|-------|-------|--------|\n")

                for ind_id, count in sorted(indicator_gaps, key=lambda x: x[1]):
                    ind_name = indicator_names.get(ind_id, ind_id)
                    frame_id = indicator_frames.get(ind_id)
                    frame_name = frame_names.get(frame_id, frame_id) if frame_id else "Unknown"
                    status = "❌ Missing" if count == 0 else f"⚠️ Only {count}"
                    f.write(f"| {ind_name} | {frame_name} | {count} | {status} |\n")

                f.write("\n")

            # Section gaps
            if section_gaps:
                f.write(f"### Frame Sections with <{MIN_TEMPLATES_PER_SECTION} Templates\n\n")
                f.write("| Frame | Section | Count | Needed |\n")
                f.write("|-------|---------|-------|--------|\n")

                for frame_id, section, count in sorted(section_gaps):
                    frame_name = frame_names.get(frame_id, frame_id)
                    needed = MIN_TEMPLATES_PER_SECTION - count
                    f.write(f"| {frame_name} | {section.replace('_', ' ').title()} | {count} | +{needed} |\n")

                f.write("\n")

            # Summary
            f.write("## Action Required\n\n")
            if indicator_gaps:
                f.write(f"- Add templates for **{len(indicator_gaps)} indicators** below threshold\n")
            if section_gaps:
                f.write(f"- Add templates for **{len(section_gaps)} frame sections** below threshold\n")

        f.write("\n## Thresholds\n\n")
        f.write(f"- Minimum templates per indicator: **{MIN_TEMPLATES_PER_INDICATOR}**\n")
        f.write(f"- Minimum templates per section: **{MIN_TEMPLATES_PER_SECTION}**\n")

    print(f"✓ Gaps report generated: {output_path}")

    if critical_gaps_exist:
        print("\n⚠️  Critical gaps identified. Review reports/gaps.md")
        return 1
    else:
        print("\n✅ No critical gaps found.")
        return 0


if __name__ == "__main__":
    sys.exit(generate_gaps_report())
