"""Generate coverage report showing template distribution across frames and indicators.

This script analyzes the template library and taxonomy to produce a coverage report
showing how many templates exist per frame, per indicator, and per section.

Output: reports/coverage.md
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from ruamel.yaml import YAML

WORKSPACE_ROOT = Path(__file__).resolve().parents[1]


def load_yaml(path: Path) -> dict:
    """Load YAML file and return parsed data."""
    yaml = YAML(typ="safe")
    return yaml.load(path)


def generate_coverage_report() -> None:
    """Generate coverage report markdown file."""
    # Load data
    templates_path = WORKSPACE_ROOT / "templates" / "comment_templates.yaml"
    indicators_path = WORKSPACE_ROOT / "taxonomy" / "indicators.yaml"
    frames_path = WORKSPACE_ROOT / "taxonomy" / "frames.yaml"

    templates_data = load_yaml(templates_path)
    indicators_data = load_yaml(indicators_path)
    frames_data = load_yaml(frames_path)

    templates = templates_data.get("templates", [])
    indicators = indicators_data.get("indicators", [])
    frames = frames_data.get("frames", [])

    # Build mappings
    frame_names = {f["id"]: f["name"] for f in frames}
    indicator_names = {i["id"]: i["name"] for i in indicators}

    # Count templates per frame
    frame_counts: dict[str, int] = defaultdict(int)
    for tmpl in templates:
        frame_id = tmpl.get("frame")
        if frame_id:
            frame_counts[frame_id] += 1

    # Count templates per frame per section
    frame_section_counts: dict[tuple[str, str], int] = defaultdict(int)
    for tmpl in templates:
        frame_id = tmpl.get("frame")
        section = tmpl.get("section")
        if frame_id and section:
            frame_section_counts[(frame_id, section)] += 1

    # Count templates per indicator
    indicator_counts: dict[str, int] = defaultdict(int)
    for tmpl in templates:
        tmpl_indicators = tmpl.get("indicators", [])
        for ind_id in tmpl_indicators:
            indicator_counts[ind_id] += 1

    # Calculate overall coverage
    total_templates = len(templates)
    total_frames = len(frames)
    total_indicators = len(indicators)

    indicators_with_templates = sum(1 for count in indicator_counts.values() if count > 0)
    indicator_coverage_pct = (indicators_with_templates / total_indicators * 100) if total_indicators > 0 else 0

    # Generate markdown report
    output_path = WORKSPACE_ROOT / "reports" / "coverage.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8") as f:
        f.write("# Template Coverage Report\n\n")
        f.write("> Auto-generated by `scripts/generate_coverage_report.py`\n\n")
        f.write("## Summary\n\n")
        f.write(f"- **Total Templates**: {total_templates}\n")
        f.write(f"- **Total Frames**: {total_frames}\n")
        f.write(f"- **Total Indicators**: {total_indicators}\n")
        f.write(
            f"- **Indicators with Templates**: "
            f"{indicators_with_templates}/{total_indicators} "
            f"({indicator_coverage_pct:.1f}%)\n\n"
        )

        # Templates per frame
        f.write("## Templates per Frame\n\n")
        f.write("| Frame | Templates | Per Section |\n")
        f.write("|-------|-----------|-------------|\n")

        sections = ["key_learning", "growth", "next_steps"]
        for frame_id in sorted(frame_counts.keys()):
            frame_name = frame_names.get(frame_id, frame_id)
            total = frame_counts[frame_id]
            section_breakdown = " / ".join(str(frame_section_counts.get((frame_id, s), 0)) for s in sections)
            f.write(f"| {frame_name} | {total} | {section_breakdown} |\n")

        # Templates per indicator
        f.write("\n## Templates per Indicator\n\n")
        f.write("| Indicator | Count |\n")
        f.write("|-----------|-------|\n")

        # Group by frame
        for frame in frames:
            frame_id = frame["id"]
            frame_name = frame_names[frame_id]
            f.write(f"| **{frame_name}** | |\n")

            frame_indicators = [ind["id"] for ind in frame.get("indicators", [])]
            for ind_id in frame_indicators:
                ind_name = indicator_names.get(ind_id, ind_id)
                count = indicator_counts.get(ind_id, 0)
                status = "✓" if count >= 2 else "⚠️" if count == 1 else "❌"
                f.write(f"| {status} {ind_name} | {count} |\n")

        # Section distribution
        f.write("\n## Section Distribution\n\n")
        f.write("| Frame | Key Learning | Growth | Next Steps |\n")
        f.write("|-------|--------------|--------|------------|\n")

        for frame_id in sorted(frame_counts.keys()):
            frame_name = frame_names.get(frame_id, frame_id)
            kl = frame_section_counts.get((frame_id, "key_learning"), 0)
            gr = frame_section_counts.get((frame_id, "growth"), 0)
            ns = frame_section_counts.get((frame_id, "next_steps"), 0)
            f.write(f"| {frame_name} | {kl} | {gr} | {ns} |\n")

        f.write("\n## Legend\n\n")
        f.write("- ✓ Indicator has 2+ templates (good coverage)\n")
        f.write("- ⚠️ Indicator has 1 template (minimal coverage)\n")
        f.write("- ❌ Indicator has 0 templates (gap)\n")

    print(f"✓ Coverage report generated: {output_path}")


if __name__ == "__main__":
    generate_coverage_report()
